### PR TITLE
Update

### PR DESCRIPTION
**Pull request by boyan-simeonov**

### CODE REVIEW

**Comment by jimkont** [comment]
Thanks! Could you please place the BG configuration in alphabetical order?

**Comment by boyan-simeonov** [comment]
OK, I will do it in a few minutes

**Comment by boyan-simeonov** [comment]
Should I create new pull request now?

**Comment by jimkont** [comment]
No, commit the change on the same Branch

**Comment by boyan-simeonov** [comment]
I think now is OK, the new version of the files appears in files changed

**Comment by jimkont** [comment]
perfect! Thanks Boyan

**Pull request merged**
