### PR TITLE
add one for sv

### PR DESCRIPTION
**Pull request by jimregan**

### CODE REVIEW

**Comment by jcsahnwaldt** [comment]
@jimregan I guess editing the lists is awkward, the format wasn't meant for human consumption. The ignore lists can be edited directly through the browser, you just need a password.   @jimkont Do you have the password? Could you pass it on to @jimregan and others who want to edit the lists?

**Comment by jimkont** [comment]
right, anyone who wants the password ping me offline.
@jcsahnwaldt haven't checked, are the ignored lists saved back to the files?

**Comment by jcsahnwaldt** [comment]
@jimkont Each time someone makes a change, they are [saved on the server](/dbpedia/extraction-framework/blob/master/server/src/main/scala/org/dbpedia/extraction/server/stats/IgnoreList.scala#L101) in the location where they were checked out from the repo. Then they should be committed back into the repo. To avoid merge conflicts, It might make sense to have a cron job commit them every few hours or so...

**Comment by jcsahnwaldt** [comment]
See https://github.com/dbpedia/extraction-framework/issues/375

**Pull request merged**
