### PR TITLE
Maven central deployment

### PR DESCRIPTION
**Pull request by sandroacoelho**
- Added required info and in poms (for master);

Could you, please, might check the new info added in pom(mainly licenses and description) ?

Tasks
- [X] - Release 4.1 (master / snapshot)  
- [X] - Comment on ticket when you promoted your first release
- [X] - Release 4.0 
- [X] - Release 3.9

### CODE REVIEW

**Comment by jimkont** [comment]
Cool thanks @sandroacoelho 
we had some more code left to commit till 4.1 but it's ok

travis fails because of the gpg plugin, what you can do to avoid this is to put some dependencies in a release profile

see: https://github.com/AKSW/RDFUnit/blob/master/pom.xml#L423-L519

it will also make things easier if we use the release plugin and bind it to the release profile again like
https://github.com/AKSW/RDFUnit/blob/master/pom.xml#L236-L248

**Comment by jimkont** [comment]
other than that the description metadata look good!

**Comment by jimkont** [comment]
Additional info,

you can only promote to maven central v4.0, 3.9 and before have dependencies to artifacts not on central and cannot be deployed

**Comment by sandroacoelho** [comment]
Hi @jimkont 

Thank you for review it. I have done.

About releases 3.9 and 4.0, I created two branches ([maven-central-3.9](https://github.com/sandroacoelho/extraction-framework/tree/maven-central-3.9)  and [maven-central-4.0](https://github.com/sandroacoelho/extraction-framework/tree/maven-central-4.0)) and release it without live module that depends of some artifacts from ASKW repository. Should I send a PR for them?

**Comment by jimkont** [comment]
+1

**Pull request merged**
