### PR TITLE
enable empty properties on IntermediateNodeMapping

### PR DESCRIPTION
**Pull request by Nono314**
see #364 
if nobody opposes the change...

### CODE REVIEW

**Comment by jimkont** [comment]
+1 from me, looks safe but don't know the reason we made that check
@jcsahnwaldt any comment?

**Comment by Nono314** [comment]
Any update about this one?

I keep founding more and more examples with missing extracted data caused by this bug.
For example in `fr` most politicians are missing their primary function because the template has all possible keys for function1 listed but only some assigned values. 
This may also be the reason why OfficeHolder in `en` is strangely using IntermediateNode with very few fields and just piling up everything else in single properties (you can't easily tell who succeeded to [George W. Bush] (http://dbpedia.org/page/George_W._Bush) as President!)

**Comment by jimkont** [comment]
Merged! Thanks for identifying this @Nono314 
The code is already deployed on the mapping server. If this is working properly you can close #364

**Comment by Nono314** [comment]
@jimkont thanks!

**Pull request merged**
