### PR TITLE
DateIntervalMapping i18n

### PR DESCRIPTION
**Pull request by Nono314**
* implement a "since xxx" construct common in Fr
* implement a "xxx onward" construct common in Es
* allow several words per language for "present"
* adding more languages in config file
* custom (textual) separators for DateIntervalMapping (language dependant): allows for "de ... à ..." used in Fr
* replicate splitPropertyNodes mechanism already used for all dataparsers
* create unit tests

### CODE REVIEW

**Comment by Nono314** [comment]
@jimkont 
Hi Dimitris,
What is the status of that PR? Were you still waiting for something on my side?
Or did it just slip through?

I think there were some interesting points in this... Would be nice to have them for next release :-)

**Comment by jimkont** [comment]
Actually I don't remember :) will check and get back at this shortly

**Comment by jimkont** [comment]
Looks good to me but I see that you now support multiple intervals.
This is more of a modeling problem but when all these triples are assigned to a resource one cannot distinguish the original ranges.
@jcsahnwaldt any comments on this?

**Comment by jcsahnwaldt** [comment]
No, sorry.

**Comment by jimkont** [comment]
Well no one does anymore :)

**Comment by Nono314** [comment]
Yes, I know this behaviour is not ideal, but given that the current code does not even handle the first one correctly in that case (taking the first year as both start and end), I think it's still better...

There's no way I can think of to group together the respective start and end of an interval. Most of the cases will probably be direct properties of an entity, and in case it's an intermediate node we do not have access to the parent context to duplicate it.

One way to go would be to compute the enclosing interval, which is probably what people expect in the most common case of activeYears. But this may be going a bit too far, not just extracting but making assumptions?

Any thought?

**Comment by jimkont** [comment]
One option would be to create an intermediate node URI with __period__1 suffix that would be of time dbo:Period and has predefined start/end fields.
Then the mapping would be defined with a new property instead of two (atm) that has dbo:Period as range

**Comment by Nono314** [comment]
That would be great, and make a bunch of properties in the ontology much simpler! (there's a very common pattern with 4 properties combining start/end with date/year)

But this would also have a high impact on a large number of mappings and potentially on user applications based on DBPedia...
I was reasoning with a fixed ontology, but if the ontology committee thinks that would be a good move, implementing this solution in the code will probably not be the toughest part!

Just let me know.

**Comment by jimkont** [comment]
ok, let's do it like this:
- allow only one period for now e.g. get only the first valid chunk
- add a descriptive comment above that also links here

I will merge the code and we will discuss this with the ontology committee and see what they propose instead

**Comment by Nono314** [comment]
@jimkont: Here you are!

**Pull request merged**
