### PR TITLE
Update ExceptionMapper.scala

### PR DESCRIPTION
**Pull request by gone-phishing**
Removing deprecated getStackTraceString method

### CODE REVIEW

**Comment by jimkont** [comment]
Thanks a lot!
Can you make `sw` local (immutable) to be safe? I didn't write any of the server code and maybe there is some thread race condition that corrupts the string value

**Comment by gone-phishing** [comment]
@jimkont I have pushed a new commit that makes the sw variable synchronized and hence thread safe.

**Comment by jcsahnwaldt** [comment]
That doesn't work. Please make sw a local variable in toResponse().

**Comment by gone-phishing** [comment]
@jcsahnwaldt I have included sw in the toResponse method making it local here and removed the unnecessary sync part

**Comment by jimkont** [comment]
Thanks again @gone-phishing

**Pull request merged**
