### PR TITLE
FlagTemplateParser: support full country name templates + perf improvements

### PR DESCRIPTION
**Pull request by Nono314**
- support full country name templates eg {{France}} not just {{FRA}}, used in `fr`
- performance improvements by caching code-generated config

second part of issue #360

### CODE REVIEW

**Comment by jimkont** [comment]
Thanks! The only think we'd need to merge this is to make access & update of the map variables thread-safe.
This shouldn't be a problem in normal dump extraction but might be in the server module.

**Comment by Nono314** [comment]
I'm not very familiar with scala... What would be the preferred way? Just adding a synchonized block on the access methods? Or is there a concurrent version of the collection classes?

**Comment by Nono314** [comment]
Any feedback on this?

**Comment by jimkont** [comment]
Hi, can you ping me offline you name and affiliation? We want give credit to people who contributed in this release

**Pull request merged**
